Blog/Blog/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path("ckeditor5/", include('django_ckeditor_5.urls')),
    path('', include('Blog_app.urls')),
    path('',include('user_app.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Blog/user_app/urls.py
from django.contrib import admin
from django.urls import path
from . import views

urlpatterns = [
    path('profile',views.profileView, name='profile'),
    
    # profile_image
    path('profile_image_upload/', views.profile_image_upload, name='profile_image_upload'),

    path('update_personal_info/', views.update_personal_info, name='update_personal_info'),

    # update email
    path('update_email/', views.update_email,name='update_email'),

    # update contact
    path('update_contact/', views.update_contact, name='update_contact'),

    # user releted blogs
    path('user_blogs/',views.user_blogs,name='user_blogs'),
    
    # handle edited blog post
    path('edit/<slug:post_slug>/',views.edit_blog,name='edit_blog'),
    
    # delete blog post
    path('delete_blog/<slug:post_slug>/',views.delete_blog,name='delete_blog'),
]

Blog/Blog_app/models.py
from django.db import models
from django.utils.text import slugify
from django.db.models.signals import pre_save
from django_ckeditor_5.fields import CKEditor5Field
from django.utils.timezone import now
from django.contrib.auth.models import User
from user_app.models import UserProfileModel

# Create your models here.
class CategoryModel(models.Model):
    categoryName = models.CharField(max_length=100,unique=True)
    categoryImage = models.ImageField(upload_to='CategoryImage',null=True,blank=True)

    def __str__(self):
        return self.categoryName
    
class PostModel(models.Model):
    STATUS = (
        ('0','Draft'),
        ('1','Publish'),
    )
    SECTION = (
        ('Popular','Popular'),
        ('Recent','Recent'),
        ('Editors_Pick','Editors_Pick'),
        ('Trending','Trending'),
        ('Inspiration','Inspiration'),
        ('Latest_Post','Latest_Post'),
    )

    post_image = models.ImageField(upload_to='PostImages',null=True,blank=True)
    title = models.CharField(max_length=200)
    author = models.ForeignKey(User,on_delete=models.CASCADE, blank=True,null=True, related_name='user_posts')
    category = models.ForeignKey(CategoryModel,on_delete=models.CASCADE)
    date = models.DateField(auto_now_add=True)
    content = CKEditor5Field(config_name='extends')
    slug = models.SlugField(max_length=500,null=True,blank=True,unique=True)
    status = models.CharField(choices=STATUS,max_length=100,default='0')
    section = models.CharField(choices=SECTION,max_length=200)
    main_post = models.BooleanField(default=False)
    views = models.IntegerField(default=0)
    likes = models.ManyToManyField(User,related_name='blog_posts')

    def __str__(self):
        return self.title
    
def create_slug(instance,new_slug=None):
    slug = slugify(instance.title)
    if new_slug is not None:
        slug = new_slug
    qs = PostModel.objects.filter(slug=slug).order_by('-id')
    exists = qs.exists()
    if exists:
        new_slug = "%s-%s" % (slug,qs.first().id)
        return create_slug(instance,new_slug=new_slug)
    return slug

def pre_save_post_reciver(sender,instance,*args,**kwargs):
    if not instance.slug:
        instance.slug = create_slug(instance)
pre_save.connect(pre_save_post_reciver,PostModel)

class TagModel(models.Model):
    name = models.CharField(max_length=100)
    post = models.ForeignKey(PostModel,on_delete=models.CASCADE)

    def __str__(self):
        return self.name

class blogcomment(models.Model):
    sno = models.AutoField(primary_key=True)
    user  = models.ForeignKey(User,on_delete=models.CASCADE,null=True)
    profile = models.ForeignKey(UserProfileModel, on_delete=models.CASCADE, null=True, blank=True)
    comment = models.TextField()
    post = models.ForeignKey(PostModel,on_delete=models.CASCADE,related_name='comments')
    parent = models.ForeignKey('self',on_delete=models.CASCADE,null=True)
    timestamp = models.DateTimeField(default=now)

    def __str__(self):
        return f"sno:{self.sno} name:{self.user} comment:{self.comment}"

class contactModel(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField()
    message = models.TextField()

    def __str__(self):
        return self.name

class subscriptionModel(models.Model):
    email = models.EmailField()

    def __str__(self):
        return self.email

Blog/user_app/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class UserProfileModel(models.Model):
    user  = models.ForeignKey(User,on_delete=models.CASCADE,null=True)
    firstname = models.CharField(max_length=50,blank=True)
    lastname = models.CharField(max_length=50,blank=True)
    GENDER = (
        ('M','Male'),
        ('F','Female'),
    )

    gender = models.CharField(choices=GENDER,max_length=200)
    email = models.EmailField()
    mobile = models.CharField(max_length=10)
    profile_image = models.ImageField(upload_to='Profile_image', blank=True)

    def __str__(self):
        return self.user.username
    

Blog/user_app/views.py
from django.shortcuts import render,redirect,get_object_or_404
from user_app.models import UserProfileModel
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from Blog_app.models import PostModel
from Blog_app.forms import BlogPostForm


# Create your views here.
@login_required
def profileView(request):
    userprofile = UserProfileModel.objects.get(user=request.user) 
    userprofile.email = User.email
    userprofile.save() 
    context={
        'profile':userprofile,
    }
    return render(request,'profile.html',context)

@login_required
def profile_image_upload(request):
    if request.method == 'POST':
        image = request.FILES.get('profile_photo')  # Use request.FILES to get the uploaded file
        user = request.user
        profile = UserProfileModel.objects.get_or_create(user=user)[0]  # Create the profile if it doesn't exist
        if image:  # Check if a file was provided
            profile.profile_image = image
            profile.save()
            print("Image saved!")

    return redirect('profile')

@login_required
def update_personal_info(request):
    profile = UserProfileModel.objects.get(user=request.user)
    if request.method == 'POST':
        profile.firstname = request.POST.get('firstname')
        profile.lastname = request.POST.get('lastname')
        profile.gender = request.POST.get('gender')
        profile.save()
        return redirect('profile')

@login_required
def update_email(request):
    user = request.user
    if request.method == "POST":
        new_email = request.POST.get('email')
        user.email = new_email
        user.save()
        return redirect('profile')

@login_required
def update_contact(request):
    profile = UserProfileModel.objects.get(user=request.user)
    if request.method == "POST":
        new_contact = request.POST.get('mobileNumber')
        profile.mobile = new_contact
        profile.save()
        return redirect('profile')
    

@login_required
def user_blogs(request):
    user = request.user
    blogs  = user.user_posts.all()
    context = {
        'blogs':blogs,
    }
    return render(request,'user_blogs.html',context)


@login_required
def edit_blog(request,post_slug):
    try:
        post = PostModel.objects.get(slug=post_slug,author=request.user)
    except PostModel.DoesNotExist:
        return redirect('user_blogs')
    if request.method == "POST":
        form = BlogPostForm(request.POST,request.FILES,instance=post)
        if form.is_valid():
            form.save(user=request.user)
            return redirect('user_blogs')
    else:
        form = BlogPostForm(instance = post)    
    return render(request,'edit_blog.html',{'form':form,'post':post})


@login_required
def delete_blog(request,post_slug):
    blog  = PostModel.objects.get(slug=post_slug)
    blog.delete()
    return redirect('user_blogs')

Blog/user_app/templates/edit_blog.html
{% extends 'Main/base.html' %}
{% load static %}
{% block content %}

    <!-- page header -->
    <section class="page-header">
        <div class="container-xl">
            <div class="text-center">
                <h1 class="mt-0 mb-2">Edit Blog</h1>
                <nav aria-label="breadcrumb">
                    <ol class="breadcrumb justify-content-center mb-0">
                        <li class="breadcrumb-item"><a href="{% url "home" %}">Home</a></li>
                        <li class="breadcrumb-item active" aria-current="page">Edit Blog</li>
                    </ol>
                </nav>
            </div>
        </div>
    </section> 

    <!-- section main content -->
	<section class="main-content">
		<div class="container-xl">
			<div class="row gy-4">
				<div class="col-lg-12">
					<div class="page-content bordered rounded padding-30 aboutusdiv">
                        {{ form.media }} {% comment "Required for styling/js to make ckeditor5 work" %}{% endcomment %}
                        <form method="POST" enctype="multipart/form-data">
                            {% csrf_token %}
                            <label for="id_post_image">Current Image:</label>
                            {% if form.instance.post_image %}
                                <img src="{{ form.instance.post_image.url }}" alt="Current Image" style="max-height: 200px; margin-bottom: 10px;"/>
                                <p style="word-wrap:break-word">Current File: {{ form.instance.post_image }}</p>
                            {% else %}
                                <p>No file uploaded.</p>
                            {% endif %}
                            {{form.as_p}}
                            <button type="submit" class="btn btn-default">Edit</button>
                            <button type="button" class ="btn btn-default" onclick="window.location.href='{% url 'delete_blog' form.instance.slug %}'">Delete</button>
                            <button type="button" class="btn btn-default" onclick="window.location.href='{% url 'user_blogs' %}'">Cancel</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </section>

{% endblock %}

Blog/user_app/templates/user_blogs.html
{% extends 'Main/base.html' %}
{% load static %}
{% block content %}
{% load humanize %}

    

    <!-- section main content -->
	<section class="main-content-lg" style="margin-top:0;">
        <div class="container-minimal" style="max-width:700px;">
            {% for i in blogs %}
                <div class="post post-xl">
                    <!-- post details -->
                    <div class="post-top" style="padding:0px;">
                        <ul class="meta list-inline mb-0">
                            <li class="list-inline-item"><a href="#"><img src="{% static 'images/other/author-sm.png' %}" class="author" alt="author"/>{{i.author}}</a></li>
                            {% comment %} <li class="list-inline-item">{{i.date}}</li> {% endcomment %}
                            <li class="list-inline-item"><i class="icon-eye"></i> {{i.views}}</li>
							<li class="list-inline-item"><i class="icon-heart"></i> {{ i.likes.count }}</li>
							<li class="list-inline-item"><i class="icon-bubble"></i> {{ i.comments.count }}</li>
                            <li class="list-inline-item"><i class="category-badge" style="color:white;">{{i.get_status_display}}</i></li>
                            <div class="custom-dropdown-container">
                                <li class="list-inline-item dropdown">
                                    <i class="icon-options-vertical" onclick="toggleDropdown()"></i>
                                    <ul class="dropdown-menu">
                                        <li><a href="{% url "edit_blog" i.slug %}" class="dropdown-item">Edit</a></li>
                                        <li><a href="{% url "delete_blog" i.slug %}"class="dropdown-item">Delete</a></li>
                                    </ul>
                                </li>
                            </div>
                        </ul>
                        <h5 class="post-title mb-0 mt-4"><a href="{% url 'postdetail' i.slug %}">{{i.title}}</a></h5>
                    </div>
                    <!-- thumbnail -->
                    <div class="thumb rounded">
                        <a href="{% url 'postbycat' i.category.categoryName %}" class="category-badge lg position-absolute">{{i.category}}</a>
                        <span class="post-format">
                            <i class="icon-picture"></i>
                        </span>
                        <a href="{% url 'postdetail' i.slug %}">
                            <div class="inner">
                                <img src="{{i.post_image.url}}" alt="{{i.title}}" />
                            </div>
                        </a>
                    </div>
                    <!-- details -->
                    <div class="details" style="padding: 50px 0px 50px;">
                        <p class="excerpt mb-0">{{ i.content|truncatewords_html:60|safe }}</p>
                    </div>
                    <!--share icon-->
                    <div class="post-bottom clearfix d-flex align-items-center" style="margin:0px;">
                        <div class="social-share me-auto">
                            <button class="toggle-button icon-share"></button>
                            <ul class="icons list-unstyled list-inline mb-0">
                                <li class="list-inline-item"><a href="#"><i class="fab fa-facebook-f"></i></a></li>
                                <li class="list-inline-item"><a href="#"><i class="fab fa-twitter"></i></a></li>
                                <li class="list-inline-item"><a href="#"><i class="fab fa-linkedin-in"></i></a></li>
                                <li class="list-inline-item"><a href="#"><i class="fab fa-pinterest"></i></a></li>
                                <li class="list-inline-item"><a href="#"><i class="fab fa-telegram-plane"></i></a></li>
                                <li class="list-inline-item"><a href="#"><i class="far fa-envelope"></i></a></li>
                            </ul>
                        </div>
                        <div class="float-end d-none d-md-block">
                            <a href="{% url 'postdetail' i.slug %}" class="more-link">Continue reading<i class="icon-arrow-right"></i></a>
                        </div>
                        <div class="more-button d-block d-md-none float-end">
                            <a href="{% url 'postdetail' i.slug %}" class="mobile-more-link" style="color:#FE4F70;">Continue reading<i class="icon-arrow-right"></i></a>
                        </div>
                    </div>
                </div>
                {% endfor %}
                <!-- pagination -->
                <nav>
                    <ul class="pagination justify-content-center">
                        <li class="page-item active" aria-current="page">
                            <span class="page-link">1</span>
                        </li>
                        <li class="page-item"><a class="page-link" href="#">2</a></li>
                        <li class="page-item"><a class="page-link" href="#">3</a></li>
                    </ul>
                </nav>
                <!-- instagram feed -->
                <div class="instagram">
                    <div class="container-xl">
                        <!-- button -->
                        <a href="#" class="btn btn-default btn-instagram">@Katen on Instagram</a>
                        <!-- images -->
                        <div class="instagram-feed d-flex flex-wrap">
                            <div class="insta-item col-sm-2 col-6 col-md-2">
                                <a href="#">
                                    <img src="{% static 'images/insta/insta-1.jpg' %}" alt="insta-title" />
                                </a>
                            </div>
                            <div class="insta-item col-sm-2 col-6 col-md-2">
                                <a href="#">
                                    <img src="{% static 'images/insta/insta-2.jpg' %}" alt="insta-title" />
                                </a>
                            </div>
                            <div class="insta-item col-sm-2 col-6 col-md-2">
                                <a href="#">
                                    <img src="{% static 'images/insta/insta-3.jpg' %}" alt="insta-title" />
                                </a>
                            </div>
                            <div class="insta-item col-sm-2 col-6 col-md-2">
                                <a href="#">
                                    <img src="{% static 'images/insta/insta-4.jpg' %}" alt="insta-title" />
                                </a>
                            </div>
                            <div class="insta-item col-sm-2 col-6 col-md-2">
                                <a href="#">
                                    <img src="{% static 'images/insta/insta-5.jpg' %}" alt="insta-title" />
                                </a>
                            </div>
                            <div class="insta-item col-sm-2 col-6 col-md-2">
                                <a href="#">
                                    <img src="{% static 'images/insta/insta-6.jpg' %}" alt="insta-title" />
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
{% endblock %}